### PR TITLE
bump maki version to newest release

### PR DESCRIPTION
**Pull request by lyzidiamond**
:bulb:

### CODE REVIEW

**Comment by lyzidiamond** [comment]
@flippmoke Can you take a look at the failing Travis test here? It's looking like maybe something related to whatever version of Mapnik this project is using.

**Comment by flippmoke** [comment]
This looks like a problem related to installing two different versions of mapnik at the same time. 

blend@1.0.2
│ └─┬ mapnik@3.2.0

Blend is pulling in a different version.

**Comment by lyzidiamond** [comment]
@flippmoke how to resolve?

**Comment by lyzidiamond** [comment]
Resolved this issue with https://github.com/mapbox/node-blend/pull/60. Merging.

**Pull request merged**
